export { apiClient } from './client'
export { authApi } from './auth'
export type { AuthResponse, UserProfile } from './auth'
export { opportunitiesApi } from './opportunities'
export type { Opportunity, PaginatedOpportunities, DashboardMetrics } from './opportunities'
export { contactsApi } from './contacts'
export type { Contact, PaginatedContacts } from './contacts'
export { usersApi } from './users'
export type { User, PaginatedUsers } from './users'
